spring:
  application:
    name: kafka-sample
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      enable-auto-commit: true
      auto-commit-interval: 100
      auto-offset-reset: latest
      group-id: sample
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    producer:
      retries: 1
      batch-size: 256
      buffer-memory: 33554432

